### ISSUE TITLE
ShowAdvancedRightNotification?

### ISSUE THREAD

**Issue by RizzooTv** [Maybacco/mbc_notify#1]
Hello, I use vorp_core, how do I make sure that it shows the item image with mbc_notify:ShowAdvancedRightNotification? always get an error https://prnt.sc/FYti1avGCfYT

regards

**Comment by Maybacco** [comment]
Hi! You can find the correct textures at:

https://github.com/femga/rdr3_discoveries/tree/master/useful_info_from_rpfs/textures
